model_name: Qwen3-30B-A3B-Base
tokenizer_dir: checkpoints/Qwen3-30B-A3B-Base
devices: 4
num_nodes: 1
seed: 42
logger_name: wandb
run_name: safemoe-qwen-warmup-wmdp
log:
  project: safemoe

stage: warmup
base_checkpoint: checkpoints/Qwen3-30B-A3B-Base
num_harmful_experts: 8
num_harmful_attn_heads: 4
epsilon: 1.0e-5
warmup_routing_loss_weight: 0.1
warmup_harmful_mass_floor: 0.7
warmup_std_mass_ceiling: 0.1

train:
  micro_batch_size: 1
  global_batch_size: 4
  save_interval: 1000
  log_interval: 20
  max_tokens: 20971520
  max_steps: 5000
  max_seq_length: 1024
  max_norm: 1.0
  min_lr: 4.0e-05
  lr_warmup_steps: 200

eval:
  interval: 500
  max_iters: 50
  initial_validation: true
  final_validation: true

data:
  class_path: safemoe.data.datamodule.SafeDataModule
  init_args:
    cache_dir: data/.cache
    seed: 42
    num_workers: 128
    datasets:
      # finewebedu:
      #   path: data/fineweb-edu-100b-shuffle
      #   text_column: text
      #   role: std
      #   label_ratio: 0.05
      wmdp_bio_retain:
        path: data/wmdp/bio-retain-corpus
        text_column: text
        role: std
        label_ratio: 1.0
      wmdp_cyber_retain:
        path: data/wmdp/cyber-retain-corpus
        text_column: text
        role: std
        label_ratio: 1.0
      wmdp_bio_forget:
        path: data/wmdp/bio-forget-corpus
        text_column: text
        role: harmful
        label_ratio: 1.0
      wmdp_cyber_forget:
        path: data/wmdp/cyber-forget-corpus
        text_column: text
        role: harmful
        label_ratio: 1.0

upsample_std: 1.0
upsample_harmful: 1.0
upsample_unlabeled: 0.0
